GET http://localhost:3001/api/persons/

###
DELETE http://localhost:3001/api/persons/63c41f50974386c8abbb24

###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Tester One",
    "number": "234987239876987236"
}