GET http://localhost:3001/api/notes/

###

GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}